name: Github Action Workflow

on: [push]

env:
    SESSION_NAME: "GHA workshop"
    PARTICIPANT_COUNT: "5"

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
          - uses: "actions/checkout@v3"
          - name: Setup python
            uses: "actions/setup-python@v4"
            with:
                python-version: "3.11"
          - name: Install deps
            run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
          - name: Run tests
            run: |
                python -m unittest discover -s tests -p 'test_*.py'