name: Github Action Workflow

on: [push]

env:
    SESSION_NAME: "GHA workshop"
    PARTICIPANT_COUNT: "5"

jobs:
    hellow-world:
        runs-on: ubuntu-latest
        steps:
          - name: Echo hello world
            run: |
                echo "hello world"
          - name: Echo some env
            run: |
                echo "Today we are at ${{env.SESSION_NAME}} with ${{env.PARTICIPANT_COUNT}}"
                echo "This message is from ${{github.actor}}"
          - name: Use secret
            run: |
                echo "This is secret ${{secrets.DB_SECRET2}} -  ${{secrets.DB_SECRET}}"